version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSGRES_PW}
      POSTGRES_USER: ${POSGRES_USER}
      POSTGRES_DB: ${POSGRES_DB}
    ports:
      - 5432:5432
