version: '3.1'

services:

  api:
    build:
      context: ./api
    depends_on:
      - db
      - cache
    # restart: always
    environment:
      REDIS_PW: ${REDIS_PW}
      REDIS_HOST: cache
      POSGRES_PW: ${POSGRES_PW}
      POSGRES_USER: ${POSGRES_USER}
      POSGRES_DB: ${POSGRES_DB}
      POSGRES_PORT: ${POSGRES_PORT}
      POSGRES_HOST: db
      FLASK_ENV: app.py
      FLASK_ENV: development
      DOCKER_ENV: isSet
    volumes:
      - ./api:/app/api  #For development
    ports:
      - 5000:5000

  cache:
    image: redis:6.2-buster
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./api/cache:/usr/local/etc/redis/

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSGRES_PW}
      POSTGRES_USER: ${POSGRES_USER}
      POSTGRES_DB: ${POSGRES_DB}
    ports:
      - ${POSGRES_PORT}:${POSGRES_PORT}
    volumes:
      # - ./db_files:/var/lib/postgresql/data
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: